[package]
cairo-version = "=2.9.4"
name = "stark_brawl"
version = "1.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
spawn = "sozo execute dojo_starter-actions spawn --wait"
move = "sozo execute dojo_starter-actions move -c 1 --wait"

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", rev = "v0.9.0" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.9.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.1.1" }
cairo_assert = { git = "https://github.com/franalgaba/cairo-assert", tag = "v0.1.0" }
