name: Contracts CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install asdf
        uses: asdf-vm/actions/setup@v2

      - name: Verify asdf installation
        run: asdf --version

      - name: Install Dojo plugin
        run: |
          asdf plugin add dojo https://github.com/dojoengine/asdf-dojo
          asdf install dojo 1.5.0
          asdf global dojo 1.5.0
          asdf list dojo

      - name: Update PATH
        run: echo "$HOME/.asdf/shims" >> $GITHUB_PATH

      - name: Install Scarb plugin
        run: |
          asdf plugin add scarb
          asdf install scarb 2.10.1
          asdf global scarb 2.10.1

      - name: Create .tool-versions file
        run: |
          echo "dojo 1.5.0" > contract/.tool-versions
          echo "scarb 2.10.1" >> contract/.tool-versions

      - name: Build contracts
        working-directory: contract
        run: |
          export PATH="$HOME/.asdf/installs/dojo/1.5.0/bin:$PATH"
          sozo build

      - name: Run tests
        working-directory: contract
        run: |
          export PATH="$HOME/.asdf/installs/dojo/1.5.0/bin:$PATH"
          sozo test
          